backend:
  name: github
  repo: pepeday/saferandsafer.eu  # Replace with your repository
  branch: master  # Or master if that is your default branch
  base_url: https://api.netlify.com  # This points to Netlify's GitHub integration
  auth_endpoint: /auth
media_folder: "static/images/uploads"  # Where images will be uploaded
public_folder: "/images/uploads"       # Where the images will be accessible from
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
