name: Deploy Hugo site to GitHub Pages
on:
  push:
    branches:
      - master  # Adjust to your branch name if necessary
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to the latest version
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3  # Updated to the latest version
        with:
          hugo-version: 'latest'
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '20'  # Specify the latest Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          hugo --minify
          touch ./public/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4  # Updated to the latest version
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: pepeday/saferandsafer.eu
          publish_dir: ./public
